const syz = {
    "code": "SYZ01",
    "specificationModel": null,
    "fanSection": null,
    "pid": "0",
    "delFlag": 0,
    "type": "B06A01A03",
    "layer": 0,
    "point": "[108.7837,21.43227]",
    "startSection": null,
    "updateBy": "yel",
    "children": null,
    "route_dictText": "9#路由",
    "id": "1796032046866554881",
    "upEnable": false,
    "hasChild_dictText": null,
    "updateTime": "2024-05-31 13:02:02",
    "downEnable": false,
    "picture": null,
    "fanSection_dictText": null,
    "sortNo": 96,
    "createBy": "yel",
    "route": "B12A02",
    "endSection": null,
    "createTime": "2024-05-30 12:13:03",
    "hasChild": null,
    "applicableProcess_dictText": null,
    "name": "海上升压站",
    "sysOrgCode": null,
    "projectId": null,
    "applicableProcess": null
};

export default syz;
